coverage:
  status:
    project:
      default: false
    patch:
      default: false

ignore:
  - "StyleCop.Analyzers/StyleCop.Analyzers.CodeGeneration/"
  - "StyleCop.Analyzers/StyleCop.Analyzers.PrivateAnalyzers/"
  - "StyleCop.Analyzers/StyleCop.Analyzers.PrivateCodeFixes/"
  - "StyleCop.Analyzers/StyleCop.Analyzers.Status.Generator/"
  - "StyleCop.Analyzers/StyleCopTester/"

comment:
  layout: "diff"
