// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Emit.Lightup
{
    /// <summary>Provides lightup support for struct Microsoft.CodeAnalysis.Emit.SemanticEdit.</summary>
    public static partial class SemanticEditEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Emit.SemanticEdit";

        private delegate Microsoft.CodeAnalysis.Emit.SemanticEdit ConstructorDelegate0(global::Microsoft.CodeAnalysis.Emit.SemanticEditKind kind, global::Microsoft.CodeAnalysis.ISymbol? oldSymbol, global::Microsoft.CodeAnalysis.ISymbol? newSymbol, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::Microsoft.CodeAnalysis.SyntaxNode>? syntaxMap, global::System.Boolean preserveLocalVariables, global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper instrumentation);
        private delegate Microsoft.CodeAnalysis.Emit.SemanticEdit ConstructorDelegate1(global::Microsoft.CodeAnalysis.Emit.SemanticEditKind kind, global::Microsoft.CodeAnalysis.ISymbol? oldSymbol, global::Microsoft.CodeAnalysis.ISymbol? newSymbol, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::Microsoft.CodeAnalysis.SyntaxNode>? syntaxMap, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Nullable<global::Microsoft.CodeAnalysis.Emit.Lightup.RuntimeRudeEditWrapper>>? runtimeRudeEdit, global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper instrumentation);

        private delegate global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper InstrumentationGetterDelegate(global::Microsoft.CodeAnalysis.Emit.SemanticEdit _obj);
        private delegate global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Nullable<global::Microsoft.CodeAnalysis.Emit.Lightup.RuntimeRudeEditWrapper>>? RuntimeRudeEditGetterDelegate(global::Microsoft.CodeAnalysis.Emit.SemanticEdit _obj);

        private static readonly ConstructorDelegate0 ConstructorFunc0;
        private static readonly ConstructorDelegate1 ConstructorFunc1;

        private static readonly InstrumentationGetterDelegate InstrumentationGetterFunc;
        private static readonly RuntimeRudeEditGetterDelegate RuntimeRudeEditGetterFunc;

        static SemanticEditEx()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            ConstructorFunc0 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceConstructorAccessor<ConstructorDelegate0>(wrappedType, "kindSemanticEditKind", "oldSymbolISymbol", "newSymbolISymbol", "syntaxMapFunc`2", "preserveLocalVariablesBoolean", "instrumentationMethodInstrumentation");
            ConstructorFunc1 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceConstructorAccessor<ConstructorDelegate1>(wrappedType, "kindSemanticEditKind", "oldSymbolISymbol", "newSymbolISymbol", "syntaxMapFunc`2", "runtimeRudeEditFunc`2", "instrumentationMethodInstrumentation");

            InstrumentationGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<InstrumentationGetterDelegate>(wrappedType, nameof(Instrumentation));
            RuntimeRudeEditGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<RuntimeRudeEditGetterDelegate>(wrappedType, nameof(RuntimeRudeEdit));
        }

        /// <summary>Constructor added in version 4.6.0.0.</summary>
        public static global::Microsoft.CodeAnalysis.Emit.SemanticEdit Create(global::Microsoft.CodeAnalysis.Emit.SemanticEditKind kind, global::Microsoft.CodeAnalysis.ISymbol? oldSymbol, global::Microsoft.CodeAnalysis.ISymbol? newSymbol, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::Microsoft.CodeAnalysis.SyntaxNode>? syntaxMap, global::System.Boolean preserveLocalVariables, global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper instrumentation)
        {
            return ConstructorFunc0(kind, oldSymbol, newSymbol, syntaxMap, preserveLocalVariables, instrumentation);
        }

        /// <summary>Constructor added in version 4.9.0.0.</summary>
        public static global::Microsoft.CodeAnalysis.Emit.SemanticEdit Create(global::Microsoft.CodeAnalysis.Emit.SemanticEditKind kind, global::Microsoft.CodeAnalysis.ISymbol? oldSymbol, global::Microsoft.CodeAnalysis.ISymbol? newSymbol, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::Microsoft.CodeAnalysis.SyntaxNode>? syntaxMap, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Nullable<global::Microsoft.CodeAnalysis.Emit.Lightup.RuntimeRudeEditWrapper>>? runtimeRudeEdit, global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper instrumentation)
        {
            return ConstructorFunc1(kind, oldSymbol, newSymbol, syntaxMap, runtimeRudeEdit, instrumentation);
        }

        /// <summary>Property added in version 4.6.0.0.</summary>
        public static global::Microsoft.CodeAnalysis.Emit.Lightup.MethodInstrumentationWrapper Instrumentation(this global::Microsoft.CodeAnalysis.Emit.SemanticEdit _obj)
        {
            return InstrumentationGetterFunc(_obj);
        }

        /// <summary>Property added in version 4.9.0.0.</summary>
        public static global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Nullable<global::Microsoft.CodeAnalysis.Emit.Lightup.RuntimeRudeEditWrapper>>? RuntimeRudeEdit(this global::Microsoft.CodeAnalysis.Emit.SemanticEdit _obj)
        {
            return RuntimeRudeEditGetterFunc(_obj);
        }
    }
}
