// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.CSharp.Syntax.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax.</summary>
    public static partial class TypeSyntaxEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax";

        private delegate global::System.Boolean IsNintGetterDelegate(global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj);
        private delegate global::System.Boolean IsNotNullGetterDelegate(global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj);
        private delegate global::System.Boolean IsNuintGetterDelegate(global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj);
        private delegate global::System.Boolean IsUnmanagedGetterDelegate(global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj);

        private static readonly IsNintGetterDelegate IsNintGetterFunc;
        private static readonly IsNotNullGetterDelegate IsNotNullGetterFunc;
        private static readonly IsNuintGetterDelegate IsNuintGetterFunc;
        private static readonly IsUnmanagedGetterDelegate IsUnmanagedGetterFunc;

        static TypeSyntaxEx()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.FindType(WrappedTypeName);

            IsNintGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceGetAccessor<IsNintGetterDelegate>(wrappedType, nameof(IsNint));
            IsNotNullGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceGetAccessor<IsNotNullGetterDelegate>(wrappedType, nameof(IsNotNull));
            IsNuintGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceGetAccessor<IsNuintGetterDelegate>(wrappedType, nameof(IsNuint));
            IsUnmanagedGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceGetAccessor<IsUnmanagedGetterDelegate>(wrappedType, nameof(IsUnmanaged));
        }

        /// <summary>Property added in version 3.7.0.0.</summary>
        public static global::System.Boolean IsNint(this global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj)
        {
            return IsNintGetterFunc(_obj);
        }

        /// <summary>Property added in version 3.2.0.0.</summary>
        public static global::System.Boolean IsNotNull(this global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj)
        {
            return IsNotNullGetterFunc(_obj);
        }

        /// <summary>Property added in version 3.7.0.0.</summary>
        public static global::System.Boolean IsNuint(this global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj)
        {
            return IsNuintGetterFunc(_obj);
        }

        /// <summary>Property added in version 2.8.0.0.</summary>
        public static global::System.Boolean IsUnmanaged(this global::Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax _obj)
        {
            return IsUnmanagedGetterFunc(_obj);
        }
    }
}
