// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    /// <summary>Provides lightup support for interface Microsoft.CodeAnalysis.Operations.ISpreadOperation. Added in version 4.9.0.0.</summary>
    public partial struct ISpreadOperationWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.ISpreadOperation";

        private static readonly global::System.Type? WrappedType;

        private delegate global::Microsoft.CodeAnalysis.Operations.Lightup.CommonConversionWrapper ElementConversionGetterDelegate(global::Microsoft.CodeAnalysis.IOperation _obj);
        private delegate global::Microsoft.CodeAnalysis.ITypeSymbol? ElementTypeGetterDelegate(global::Microsoft.CodeAnalysis.IOperation _obj);
        private delegate global::Microsoft.CodeAnalysis.IOperation OperandGetterDelegate(global::Microsoft.CodeAnalysis.IOperation _obj);

        private static readonly ElementConversionGetterDelegate ElementConversionGetterFunc;
        private static readonly ElementTypeGetterDelegate ElementTypeGetterFunc;
        private static readonly OperandGetterDelegate OperandGetterFunc;

        private readonly global::Microsoft.CodeAnalysis.IOperation wrappedObject;

        static ISpreadOperationWrapper()
        {
            WrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            ElementConversionGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<ElementConversionGetterDelegate>(WrappedType, nameof(ElementConversion));
            ElementTypeGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<ElementTypeGetterDelegate>(WrappedType, nameof(ElementType));
            OperandGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<OperandGetterDelegate>(WrappedType, nameof(Operand));
        }

        private ISpreadOperationWrapper(global::Microsoft.CodeAnalysis.IOperation obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 4.9.0.0.</summary>
        public global::Microsoft.CodeAnalysis.Operations.Lightup.CommonConversionWrapper ElementConversion
        {
            get { return ElementConversionGetterFunc(wrappedObject); }
        }

        /// <summary>Property added in version 4.9.0.0.</summary>
        public global::Microsoft.CodeAnalysis.ITypeSymbol? ElementType
        {
            get { return ElementTypeGetterFunc(wrappedObject); }
        }

        /// <summary>Property added in version 4.9.0.0.</summary>
        public global::Microsoft.CodeAnalysis.IOperation Operand
        {
            get { return OperandGetterFunc(wrappedObject); }
        }

        /// <summary>Returns true if the specified object is compatible with this wrapper.</summary>
        public static bool Is(global::Microsoft.CodeAnalysis.IOperation? obj)
        {
            return global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Is(obj, WrappedType);
        }

        /// <summary>Creates a wrapper object containing the specified object. If the object is not compatible with this wrapper, an exception will be thrown.</summary>
        public static ISpreadOperationWrapper Wrap(global::Microsoft.CodeAnalysis.IOperation obj)
        {
            var obj2 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Wrap<global::Microsoft.CodeAnalysis.IOperation>(obj, WrappedType);
            return new ISpreadOperationWrapper(obj2);
        }

        /// <summary>Returns the wrapped object.</summary>
        public global::Microsoft.CodeAnalysis.IOperation Unwrap()
        {
            return wrappedObject;
        }
    }
}
