
// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    internal class CSharpLightupHelper : global::CodeAnalysis.Lightup.Runtime.LightupHelper
    {
        private static readonly global::System.Reflection.Assembly Assembly = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax)).Assembly;

        public static global::System.Type? FindType(string wrappedTypeName)
        {
            return FindType(Assembly, wrappedTypeName);
        }
    }
}
