// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for interface Microsoft.CodeAnalysis.IFunctionPointerTypeSymbol. Added in version 3.7.0.0.</summary>
    public partial struct IFunctionPointerTypeSymbolWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.IFunctionPointerTypeSymbol";

        private static readonly global::System.Type? WrappedType;

        private delegate global::Microsoft.CodeAnalysis.IMethodSymbol SignatureGetterDelegate(global::Microsoft.CodeAnalysis.ITypeSymbol _obj);

        private static readonly SignatureGetterDelegate SignatureGetterFunc;

        private readonly global::Microsoft.CodeAnalysis.ITypeSymbol wrappedObject;

        static IFunctionPointerTypeSymbolWrapper()
        {
            WrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            SignatureGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<SignatureGetterDelegate>(WrappedType, nameof(Signature));
        }

        private IFunctionPointerTypeSymbolWrapper(global::Microsoft.CodeAnalysis.ITypeSymbol obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 3.7.0.0.</summary>
        public global::Microsoft.CodeAnalysis.IMethodSymbol Signature
        {
            get { return SignatureGetterFunc(wrappedObject); }
        }

        /// <summary>Returns true if the specified object is compatible with this wrapper.</summary>
        public static bool Is(global::Microsoft.CodeAnalysis.ITypeSymbol? obj)
        {
            return global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Is(obj, WrappedType);
        }

        /// <summary>Creates a wrapper object containing the specified object. If the object is not compatible with this wrapper, an exception will be thrown.</summary>
        public static IFunctionPointerTypeSymbolWrapper Wrap(global::Microsoft.CodeAnalysis.ITypeSymbol obj)
        {
            var obj2 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Wrap<global::Microsoft.CodeAnalysis.ITypeSymbol>(obj, WrappedType);
            return new IFunctionPointerTypeSymbolWrapper(obj2);
        }

        /// <summary>Returns the wrapped object.</summary>
        public global::Microsoft.CodeAnalysis.ITypeSymbol Unwrap()
        {
            return wrappedObject;
        }
    }
}
