// <auto-generated/>

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for enum Microsoft.CodeAnalysis.NullableAnnotation. Added in version 3.1.0.0.</summary>
    internal enum NullableAnnotationEx : global::System.Byte
    {
        /// <summary>Added in version 3.3.0.0.</summary>
        None = 0,

        /// <summary>Added in version 3.3.0.0.</summary>
        NotAnnotated = 1,

        /// <summary>Added in version 3.3.0.0.</summary>
        Annotated = 2,
    }
}
