// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.PortableExecutableReference.</summary>
    public static partial class PortableExecutableReferenceEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.PortableExecutableReference";

        private delegate global::Microsoft.CodeAnalysis.MetadataId GetMetadataIdDelegate0(global::Microsoft.CodeAnalysis.PortableExecutableReference _obj);

        private static readonly GetMetadataIdDelegate0 GetMetadataIdFunc0;

        static PortableExecutableReferenceEx()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            GetMetadataIdFunc0 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceMethodAccessor<GetMetadataIdDelegate0>(wrappedType, "GetMetadataId");
        }

        /// <summary>Method added in version 2.0.0.0.</summary>
        public static global::Microsoft.CodeAnalysis.MetadataId GetMetadataId(this global::Microsoft.CodeAnalysis.PortableExecutableReference _obj)
        {
            return GetMetadataIdFunc0(_obj);
        }
    }
}
