// <auto-generated/>

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for enum Microsoft.CodeAnalysis.SymbolDisplayMemberOptions.</summary>
    public static partial class SymbolDisplayMemberOptionsEx
    {
        /// <summary>Added in version 2.0.0.0.</summary>
        public const global::Microsoft.CodeAnalysis.SymbolDisplayMemberOptions IncludeRef = (global::Microsoft.CodeAnalysis.SymbolDisplayMemberOptions)128;
    }
}
