// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.SyntaxTreeOptionsProvider. Added in version 3.8.0.0.</summary>
    public partial struct SyntaxTreeOptionsProviderWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.SyntaxTreeOptionsProvider";

        private static readonly global::System.Type? WrappedType;

        private delegate global::Microsoft.CodeAnalysis.Lightup.GeneratedKindEx IsGeneratedDelegate0(global::System.Object _obj, global::Microsoft.CodeAnalysis.SyntaxTree tree, global::System.Threading.CancellationToken cancellationToken);
        private delegate global::System.Boolean TryGetDiagnosticValueDelegate0(global::System.Object _obj, global::Microsoft.CodeAnalysis.SyntaxTree tree, global::System.String diagnosticId, global::System.Threading.CancellationToken cancellationToken, out global::Microsoft.CodeAnalysis.ReportDiagnostic severity);
        private delegate global::System.Boolean TryGetGlobalDiagnosticValueDelegate0(global::System.Object _obj, global::System.String diagnosticId, global::System.Threading.CancellationToken cancellationToken, out global::Microsoft.CodeAnalysis.ReportDiagnostic severity);

        private static readonly IsGeneratedDelegate0 IsGeneratedFunc0;
        private static readonly TryGetDiagnosticValueDelegate0 TryGetDiagnosticValueFunc0;
        private static readonly TryGetGlobalDiagnosticValueDelegate0 TryGetGlobalDiagnosticValueFunc0;

        private readonly global::System.Object wrappedObject;

        static SyntaxTreeOptionsProviderWrapper()
        {
            WrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            IsGeneratedFunc0 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceMethodAccessor<IsGeneratedDelegate0>(WrappedType, "IsGenerated", "treeSyntaxTree", "cancellationTokenCancellationToken");
            TryGetDiagnosticValueFunc0 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceMethodAccessor<TryGetDiagnosticValueDelegate0>(WrappedType, "TryGetDiagnosticValue", "treeSyntaxTree", "diagnosticIdString", "cancellationTokenCancellationToken", "severityReportDiagnostic&");
            TryGetGlobalDiagnosticValueFunc0 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceMethodAccessor<TryGetGlobalDiagnosticValueDelegate0>(WrappedType, "TryGetGlobalDiagnosticValue", "diagnosticIdString", "cancellationTokenCancellationToken", "severityReportDiagnostic&");
        }

        private SyntaxTreeOptionsProviderWrapper(global::System.Object obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Returns true if the specified object is compatible with this wrapper.</summary>
        public static bool Is(global::System.Object? obj)
        {
            return global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Is(obj, WrappedType);
        }

        /// <summary>Creates a wrapper object containing the specified object. If the object is not compatible with this wrapper, an exception will be thrown.</summary>
        public static SyntaxTreeOptionsProviderWrapper Wrap(global::System.Object obj)
        {
            var obj2 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Wrap<global::System.Object>(obj, WrappedType);
            return new SyntaxTreeOptionsProviderWrapper(obj2);
        }

        /// <summary>Returns the wrapped object.</summary>
        public global::System.Object Unwrap()
        {
            return wrappedObject;
        }

        /// <summary>Method added in version 3.8.0.0.</summary>
        public global::Microsoft.CodeAnalysis.Lightup.GeneratedKindEx IsGenerated(global::Microsoft.CodeAnalysis.SyntaxTree tree, global::System.Threading.CancellationToken cancellationToken)
        {
            return IsGeneratedFunc0(wrappedObject, tree, cancellationToken);
        }

        /// <summary>Method added in version 3.8.0.0.</summary>
        public global::System.Boolean TryGetDiagnosticValue(global::Microsoft.CodeAnalysis.SyntaxTree tree, global::System.String diagnosticId, global::System.Threading.CancellationToken cancellationToken, out global::Microsoft.CodeAnalysis.ReportDiagnostic severity)
        {
            return TryGetDiagnosticValueFunc0(wrappedObject, tree, diagnosticId, cancellationToken, out severity);
        }

        /// <summary>Method added in version 3.8.0.0.</summary>
        public global::System.Boolean TryGetGlobalDiagnosticValue(global::System.String diagnosticId, global::System.Threading.CancellationToken cancellationToken, out global::Microsoft.CodeAnalysis.ReportDiagnostic severity)
        {
            return TryGetGlobalDiagnosticValueFunc0(wrappedObject, diagnosticId, cancellationToken, out severity);
        }
    }
}
