// <auto-generated/>

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for enum Microsoft.CodeAnalysis.TypeKind.</summary>
    public static partial class TypeKindEx
    {
        /// <summary>Added in version 3.7.0.0.</summary>
        public const global::Microsoft.CodeAnalysis.TypeKind FunctionPointer = (global::Microsoft.CodeAnalysis.TypeKind)13;

        /// <summary>Added in version 4.14.0.0.</summary>
        public const global::Microsoft.CodeAnalysis.TypeKind Extension = (global::Microsoft.CodeAnalysis.TypeKind)14;
    }
}
