# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
        os: [ 'windows-latest' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set Git to use long paths
      run: git config --system core.longpaths true

    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build & Test
      run: dotnet test StyleCopAnalyzers.sln -c ${{matrix.configuration}} --verbosity normal
