# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
        os: [ 'windows-latest' ]
        test: [ 'Test', 'Test.CSharp7', 'Test.CSharp8', 'Test.CSharp9', 'Test.CSharp10', 'Test.CSharp11', 'Test.CSharp12', 'Test.CSharp13', 'Test.CSharp14' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set Git to use long paths
      run: git config --system core.longpaths true

    - name: Checkout code
      uses: actions/checkout@v5
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v5

    - name: Build & Test
      run: dotnet test StyleCop.Analyzers/StyleCop.Analyzers.${{matrix.test}}/StyleCop.Analyzers.${{matrix.test}}.csproj -c ${{matrix.configuration}} --verbosity normal
