# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
        os: [ 'windows-latest' ]
        testversion: [ '6', '7', '8', '9', '10', '11', '12', '13', '14', '15' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set Git to use long paths
      run: git config --system core.longpaths true

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Restore tools
      run: dotnet tool restore

    - name: Build
      run: dotnet build -c ${{matrix.configuration}}

    - name: Test
      run: dotnet dotnet-coverage collect "dotnet test --no-build --project StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp${{matrix.testversion}}/StyleCop.Analyzers.Test.CSharp${{matrix.testversion}}.csproj -c ${{matrix.configuration}}" --output TestResults/coverage.cobertura.xml --output-format cobertura --settings CodeCoverage.config

    - name: Upload coverage
      uses: codecov/codecov-action@e53489f4d376d79066609109e7a95a29eb3740b1 # v7.0.0
      with:
        files: ./TestResults/coverage.cobertura.xml
        disable_search: true
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
